import {
  Briefcase,
  Handshake,
  Package,
  Trophy,
  Baby,
  BedDouble,
  BookOpen,
  Cake,
  Cpu,
  Flame,
  Flower2,
  Footprints,
  Gamepad2,
  Gem,
  Gift,
  Globe,
  HeartPulse,
  House,
  Landmark,
  Moon,
  PartyPopper,
  Plane,
  Repeat,
  Shirt,
  ShoppingBag,
  Sofa,
  Sparkles,
  Heart,
  Ticket,
  Utensils,
  Users,
  Egg,
  type LucideIcon,
} from "lucide-react";

export const categoryIcons: Record<string, LucideIcon> = {
  "fashion-lifestyle": Shirt,
  "e-commerce": ShoppingBag,
  "food-dining": Utensils,
  travel: Plane,
  jewellery: Gem,
  electronics: Cpu,
  "home-needs": House,
  "home-furnishings": Sofa,
  "health-beauty": HeartPulse,
  entertainment: Ticket,
  gaming: Gamepad2,
  hospitality: BedDouble,
  "international-brands": Globe,
  "sportswear-footwear": Footprints,
  subscriptions: Repeat,
  "baby-products": Baby,
  books: BookOpen,
  "finance-insurance": Landmark,
};

export const categoryTints: Record<string, string> = {
  "fashion-lifestyle": "bg-accent-soft text-accent",
  "e-commerce": "bg-brand-100 text-brand-800",
  "food-dining": "bg-[#ffe9d6] text-[#c2410c]",
  travel: "bg-sky-soft text-sky",
  jewellery: "bg-grape-soft text-grape",
  electronics: "bg-[#e0f2fe] text-[#0369a1]",
  "home-needs": "bg-mint-soft text-mint",
  "home-furnishings": "bg-[#f5ebe0] text-[#9a6b3f]",
  "health-beauty": "bg-[#fde7f3] text-[#be185d]",
  entertainment: "bg-[#fef3c7] text-[#b45309]",
  gaming: "bg-[#ede9fe] text-[#6d28d9]",
  hospitality: "bg-[#ecfccb] text-[#4d7c0f]",
  "international-brands": "bg-[#e0e7ff] text-[#4338ca]",
  "sportswear-footwear": "bg-[#dcfce7] text-[#15803d]",
  subscriptions: "bg-[#fae8ff] text-[#a21caf]",
  "baby-products": "bg-[#fff1f2] text-[#e11d48]",
  books: "bg-[#f1f5f9] text-[#334155]",
  "finance-insurance": "bg-[#ecfeff] text-[#0e7490]",
};

export const occasionIcons: Record<string, LucideIcon> = {
  birthday: Cake,
  anniversary: Heart,
  wedding: Sparkles,
  "house-warming": House,
  "new-year": PartyPopper,
  diwali: Flame,
  eid: Moon,
  rakhi: Gift,
  "valentines-day": Heart,
  "mothers-day": Flower2,
  "fathers-day": Users,
  easter: Egg,
};


export const solutionIcons: Record<string, LucideIcon> = {
  trophy: Trophy,
  handshake: Handshake,
  sparkles: Sparkles,
  package: Package,
  briefcase: Briefcase,
  heart: Heart,
};
