import brandsData from "@/data/brands.json";
import taxonomy from "@/data/taxonomy.json";

// Generated by scripts/build-brand-data.py from the root brands.ts export — do not edit by hand.

export type BrandPrice =
  | { type: "slab"; denominations: number[] }
  | { type: "range"; min: number | null; max: number | null; denominations?: number[] };

export interface Brand {
  slug: string;
  name: string;
  productName: string;
  logo: string | null;
  category: string;
  categories: string[];
  occasions: string[];
  popular: boolean;
  description: string;
  descriptionNeedsReview: boolean;
  terms: string[];
  howToRedeem: string[];
  expiry: string | null;
  price: BrandPrice;
  audience: string;
}

export interface Taxon {
  id: string;
  name: string;
}

export const brands = brandsData as Brand[];
export const categories = taxonomy.categories as Taxon[];
export const occasions = taxonomy.occasions as Taxon[];

/** Shown wherever a brand has no logo of its own. */
export const DEFAULT_BRAND_IMAGE = "/brands/default-e-gift-card.png";

export function brandImage(brand: Pick<Brand, "logo">) {
  return brand.logo ?? DEFAULT_BRAND_IMAGE;
}

const bySlug = new Map(brands.map((b) => [b.slug, b]));

export function getBrand(slug: string) {
  return bySlug.get(slug);
}

export function getCategory(id: string) {
  return categories.find((c) => c.id === id);
}

export function getOccasion(id: string) {
  return occasions.find((o) => o.id === id);
}

export function brandsInCategory(id: string) {
  return brands.filter((b) => b.categories.includes(id));
}

export function brandsForOccasion(id: string) {
  return brands.filter((b) => b.occasions.includes(id));
}

export function popularBrands(limit = 12) {
  return brands.filter((b) => b.popular && b.logo).slice(0, limit);
}

export function relatedBrands(brand: Brand, limit = 8) {
  return brands
    .filter((b) => b.slug !== brand.slug && b.categories.some((c) => brand.categories.includes(c)))
    .sort((a, b) => Number(Boolean(b.logo)) - Number(Boolean(a.logo)))
    .slice(0, limit);
}

/** Find a catalog brand by (partial) display name, used for inline mentions in content. */
export function findBrandByName(name: string) {
  const needle = name.toLowerCase();
  return brands.find((b) => b.name.toLowerCase() === needle) ?? brands.find((b) => b.name.toLowerCase().startsWith(needle));
}

const inr = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });

export function formatInr(value: number) {
  return inr.format(value);
}

export function priceSummary(price: BrandPrice) {
  if (price.type === "slab") {
    if (!price.denominations.length) return "Fixed denominations";
    const d = price.denominations;
    return d.length === 1 ? formatInr(d[0]) : `${formatInr(d[0])} – ${formatInr(d[d.length - 1])}`;
  }
  if (price.min && price.max) return `${formatInr(price.min)} – ${formatInr(price.max)}`;
  return "Flexible value";
}

export function brandInitials(name: string) {
  return name
    .replace(/[^A-Za-z0-9 ]/g, "")
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((w) => w[0]!.toUpperCase())
    .join("");
}
